apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-memory-cpu
spec:
  limits:
    - min:
        memory: 100Mi
        cpu: "0.1"
      max:
        memory: 1024Mi
        cpu: "1"
      type: Container