apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    volume: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data" # Pasta local dentro do cluster