apiVersion: v1
kind: Service
metadata:
  name: my-service-nginx
  spec:
    type: NodePort
    selector:
      run: svc-site-nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80