apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-nginx
  labels:
    app: site-nginx
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: site-nginx
      environment: dev
  template:
    metadata:
      labels:
        app: site-nginx
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
              - curl
              - -f
              - http://localhost:80/
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          startupProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5